name: Compilar APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Compilar APK con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Publicar el APK generado
        uses: actions/upload-artifact@v4
        with:
          name: taller-lutheria-apk
          path: ${{ steps.buildozer.outputs.filename }}
